version: '3'

services:
  elasticsearch:
      image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
      volumes:
        - ./data
      ports:
        - "9200:9200"
        - "9300:9300"
      environment:
        - "cluster.name=elasticsearch"
        -  discovery.type=single-node
        - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
        - "XPACK_SECURITY_ENABLED=false"
      networks:
        - elasticsearch
  web:
    build: .
    restart: always
    ports:
      - "5000:5000"
      - "8010:8010"
    networks:
      - elasticsearch
networks:
  elasticsearch:
    driver: bridge
